### ISSUE TITLE
review PLATFORMS / LABEL - Translation, add macarm vs. macx86

### ISSUE THREAD

**Issue by mbaas2** [Dyalog/CITA#10]
From Andy:

> What you might like to do sooner rather than later is to add machines with the labels "mac" and "arm" to your database so you can start to run CITA on mac_arm (mac4 and mac5 - although at the moment it's all on mac4)

**Comment by mbaas2** [comment]
Currently can't test on arm - mac4/mac5 both have `mac` & `arm` labels, they don't have `cita_latest`, so they're no candidates.
(Emailed @dyaandys on June 28th)

**Comment by mbaas2** [comment]
There's also a relation between `platforms` and `versions`: we don't have `18.2` on `arm`!

But maybe this one exception is not worth imposing the extra work related to maintaing such a list and it is 
thus justifyable to "hardcodedly" avoid every trying to run tests on `18.2 & arm`...?!

**Comment by dyaandys** [comment]
This will happen all the time.  If I add 18.2 and arm as the labels for a job, and no nodes match them, I get an error.  Can you check for that, or get a list of labels by machine and see what of the entire ∘.,/ matches ?

**Comment by dyaandys** [comment]
cita_latest exists on a mac_arm box ..

**Comment by mbaas2** [comment]
> cita_latest exists on a mac_arm box ..

yeah right, you changed it in response to my mail - i just  had not updated that comment...

**Comment by mbaas2** [comment]
> This will happen all the time. If I add 18.2 and arm as the labels for a job, and no nodes match them, I get an error. Can you check for that, or get a list of labels by machine and see what of the entire ∘.,/ matches ?

That requires more thought thinking & research than I can do at the moment - will have to get back to this after the "enclave" etc.   But maybe this time will help with "background ripening" of ideas ;)

**Comment by mbaas2** [comment]
Thank you Andy - with the code you shared on Zoom and a night to mull over it, this is easier that I thought! 🙂

**Comment by mbaas2** [comment]
closed as fixed. reopen when needed.
