### ISSUE TITLE
Cannot remove versions

### ISSUE THREAD

**Issue by rikedyp** [Dyalog/CITA#17]
```
      ]cita.aplversions ~121C32
Using list of interpreters from file "C:/Users/rpark/Documents/Dyalog APL Files/interpreters.json5"
enabled   disabled
-------   --------
121C32           
150U64           
170U64           
171C64           
180U64           
182U64           
190C64           
190U64   
```

**Comment by mbaas2** [comment]
I wasn't able to reproduce that effect (though I remember having witnessed it). 
But APLVersions has gone through some updates now and I couldn't find a case where it misbehaved. (this is currently in the "devt" branch). Pls. re-open if you find a repro with the latest changes.
