### ISSUE TITLE
Split DYALOGCITAWORKDIR into two settings

### ISSUE THREAD

**Issue by bpbecker** [Dyalog/CITA#3]
According to the Wiki, DYALOGCITAWORKDIR is mandatory and needs to be the same for all users (e.g. somewhere on the u:\ or /devt/ drive.  This means I have to be connected via the VPN, even when I just want to run tests locally.

I suggest that we have two settings, one for when running locally and one for when running via Jenkins.

Mind you, I've not experimented with CITA, so, I'm not sure the documentation aligns with the current implementation.

**Comment by mbaas2** [comment]
I'm sorry - the documentation hasn't been updated yet to align with the latest changes, and this part suffers from it.

And to answer the inherent question: `]ExecuteLocalTest` does not use `DYALOGCITAWORKDIR`, it runs the tests in a temporary folder ([739⌶0](https://help.dyalog.com/18.0/#Language/I%20Beam%20Functions/Temporary%20Directory.htm)) unless there is a explicit specification given in the `-workdir` modifier.
